Traceback (most recent call last):
  File "/Users/ethan/opt/miniconda3/envs/pythonbook3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/ethan/opt/miniconda3/envs/pythonbook3/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ethan/opt/miniconda3/envs/pythonbook3/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ethan/opt/miniconda3/envs/pythonbook3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/ethan/opt/miniconda3/envs/pythonbook3/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/ethan/opt/miniconda3/envs/pythonbook3/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/ethan/opt/miniconda3/envs/pythonbook3/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
random_stuff = ['apple', ' pear', 42]

for thing in random_stuff:
    new_thing = thing + 's'
    print(new_thing)
------------------

----- stdout -----
apples
 pears
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[5], line 4[0m
[1;32m      1[0m random_stuff [38;5;241m=[39m [[38;5;124m'[39m[38;5;124mapple[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124m pear[39m[38;5;124m'[39m, [38;5;241m42[39m]
[1;32m      3[0m [38;5;28;01mfor[39;00m thing [38;5;129;01min[39;00m random_stuff:
[0;32m----> 4[0m     new_thing [38;5;241m=[39m thing [38;5;241m+[39m [38;5;124m'[39m[38;5;124ms[39m[38;5;124m'[39m
[1;32m      5[0m     [38;5;28mprint[39m(new_thing)

[0;31mTypeError[0m: unsupported operand type(s) for +: 'int' and 'str'

